// ===========================================
// SGC - Seed Data
// Dados iniciais para desenvolvimento
// ===========================================

import type {
  Store,
  Category,
  Product,
  ProductLink,
  Coupon,
  Review,
} from './schema'

// ===========================================
// STORES
// ===========================================

export const stores: Store[] = [
  {
    id: 'store-1',
    name: 'Amazon',
    slug: 'amazon',
    logoUrl: '/stores/amazon.png',
    websiteUrl: 'https://amazon.com.br',
    affiliateProgram: 'Amazon Associates',
    commissionRate: 8,
    isActive: true,
    priority: 1,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'store-2',
    name: 'Shopee',
    slug: 'shopee',
    logoUrl: '/stores/shopee.png',
    websiteUrl: 'https://shopee.com.br',
    affiliateProgram: 'Shopee Affiliates',
    commissionRate: 10,
    isActive: true,
    priority: 2,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'store-3',
    name: 'Mercado Livre',
    slug: 'mercado-livre',
    logoUrl: '/stores/mercadolivre.png',
    websiteUrl: 'https://mercadolivre.com.br',
    affiliateProgram: 'Mercado Livre Affiliates',
    commissionRate: 6,
    isActive: true,
    priority: 3,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'store-4',
    name: 'Magazine Luiza',
    slug: 'magalu',
    logoUrl: '/stores/magalu.png',
    websiteUrl: 'https://magazineluiza.com.br',
    affiliateProgram: 'Magalu Affiliates',
    commissionRate: 5,
    isActive: true,
    priority: 4,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// ===========================================
// CATEGORIES
// ===========================================

export const categories: Category[] = [
  {
    id: 'cat-1',
    name: 'Eletrônicos',
    slug: 'eletronicos',
    description: 'Smartphones, tablets, acessórios e mais',
    icon: 'Smartphone',
    productCount: 2,
    isActive: true,
    sortOrder: 1,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'cat-2',
    name: 'Casa & Cozinha',
    slug: 'casa-cozinha',
    description: 'Eletrodomésticos, utensílios e decoração',
    icon: 'Home',
    productCount: 1,
    isActive: true,
    sortOrder: 2,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'cat-3',
    name: 'Beleza',
    slug: 'beleza',
    description: 'Skincare, maquiagem e cuidados pessoais',
    icon: 'Sparkles',
    productCount: 1,
    isActive: true,
    sortOrder: 3,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'cat-4',
    name: 'Moda',
    slug: 'moda',
    description: 'Roupas, calçados e acessórios',
    icon: 'Shirt',
    productCount: 2,
    isActive: true,
    sortOrder: 4,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'cat-5',
    name: 'Esportes',
    slug: 'esportes',
    description: 'Equipamentos, roupas e suplementos',
    icon: 'Dumbbell',
    productCount: 0,
    isActive: true,
    sortOrder: 5,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'cat-6',
    name: 'Livros',
    slug: 'livros',
    description: 'Livros físicos, e-books e audiobooks',
    icon: 'BookOpen',
    productCount: 0,
    isActive: true,
    sortOrder: 6,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

// ===========================================
// PRODUCTS
// ===========================================

export const products: Product[] = [
  {
    id: 'prod-1',
    slug: 'fone-bluetooth-premium-anc',
    name: 'Fone Bluetooth Premium com Cancelamento de Ruído',
    description: 'Fone de ouvido sem fio com tecnologia de cancelamento de ruído ativo (ANC), proporcionando uma experiência sonora imersiva. Possui bateria de longa duração de até 40 horas, conexão Bluetooth 5.3 estável e design ergonômico com almofadas de espuma memory foam para máximo conforto durante uso prolongado.',
    shortDescription: 'Fone wireless com ANC, 40h de bateria e Bluetooth 5.3',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&q=80',
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&q=80',
      'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500&q=80',
    ],
    categoryId: 'cat-1',
    tags: ['fone', 'bluetooth', 'anc', 'wireless'],
    pros: [
      'Cancelamento de ruído excelente',
      'Bateria de 40 horas',
      'Bluetooth 5.3 estável',
      'Confortável para uso prolongado',
    ],
    cons: [
      'Estojo de transporte um pouco grande',
      'Não possui certificação IP para água',
    ],
    verdict: 'Excelente opção para quem busca qualidade sonora e conforto. O ANC é um dos melhores da categoria.',
    rating: 4.7,
    reviewCount: 3,
    clickCount: 1250,
    currentPrice: 189.90,
    originalPrice: 349.90,
    discount: 46,
    status: 'active',
    isFeatured: true,
    isTopRated: true,
    publishedAt: new Date('2024-01-15'),
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'prod-2',
    slug: 'smartwatch-fitness-pro',
    name: 'Smartwatch Fitness Pro com GPS Integrado',
    description: 'Smartwatch completo para atletas e entusiastas de fitness. Possui GPS integrado de alta precisão, monitoramento cardíaco 24h, mais de 100 modos de exercício, resistência à água 5ATM e bateria que dura até 14 dias. Tela AMOLED vibrante de 1.4" com sempre ligada.',
    shortDescription: 'Smartwatch com GPS, monitor cardíaco e 14 dias de bateria',
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&q=80',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&q=80',
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=500&q=80',
    ],
    categoryId: 'cat-1',
    tags: ['smartwatch', 'fitness', 'gps', 'saúde'],
    pros: [
      'GPS muito preciso',
      'Bateria de 14 dias',
      'Monitor cardíaco confiável',
      'Resistente à água 5ATM',
    ],
    cons: [
      'Não possui NFC para pagamentos',
      'App poderia ser mais intuitivo',
    ],
    verdict: 'Ideal para praticantes de esportes que precisam de GPS confiável e bateria duradoura.',
    rating: 4.5,
    reviewCount: 1,
    clickCount: 890,
    currentPrice: 299.90,
    originalPrice: 499.90,
    discount: 40,
    status: 'active',
    isFeatured: true,
    isTopRated: false,
    publishedAt: new Date('2024-02-01'),
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'prod-3',
    slug: 'air-fryer-digital-5l',
    name: 'Air Fryer Digital 5 Litros com Painel Touch',
    description: 'Fritadeira elétrica sem óleo com capacidade de 5 litros, ideal para famílias. Possui painel touch digital com 8 funções pré-programadas, timer de até 60 minutos e temperatura ajustável de 80°C a 200°C. Cesto antiaderente removível para fácil limpeza.',
    shortDescription: 'Fritadeira sem óleo 5L com painel digital e 8 funções',
    imageUrl: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=500&q=80',
    images: [
      'https://images.unsplash.com/photo-1585515320310-259814833e62?w=500&q=80',
    ],
    categoryId: 'cat-2',
    tags: ['air fryer', 'cozinha', 'saudável', 'sem óleo'],
    pros: [
      'Capacidade ideal para família',
      'Fácil de limpar',
      'Funções pré-programadas práticas',
      'Comida crocante sem óleo',
    ],
    cons: [
      'Ocupa bastante espaço na bancada',
      'Barulho moderado durante uso',
    ],
    verdict: 'Melhor custo-benefício em air fryers. Perfeita para o dia a dia.',
    rating: 4.8,
    reviewCount: 1,
    clickCount: 2100,
    currentPrice: 249.90,
    originalPrice: 399.90,
    discount: 38,
    status: 'active',
    isFeatured: true,
    isTopRated: true,
    publishedAt: new Date('2024-01-20'),
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'prod-4',
    slug: 'kit-skincare-vitamina-c',
    name: 'Kit Skincare Completo com Vitamina C',
    description: 'Kit completo para cuidados faciais contendo sérum de vitamina C 20%, hidratante facial com ácido hialurônico e protetor solar FPS 50. Produtos dermatologicamente testados, veganos e cruelty-free. Ideal para todos os tipos de pele.',
    shortDescription: 'Kit facial com sérum vitamina C, hidratante e FPS 50',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&q=80',
    images: [
      'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&q=80',
      'https://images.unsplash.com/photo-1570194065650-d99fb4b38b15?w=500&q=80',
    ],
    categoryId: 'cat-3',
    tags: ['skincare', 'vitamina c', 'beleza', 'cuidados'],
    pros: [
      'Produtos de alta qualidade',
      'Vegano e cruelty-free',
      'Kit completo para rotina diária',
      'Resultados visíveis em 2 semanas',
    ],
    cons: [
      'Quantidade pequena de cada produto',
      'Sérum pode causar sensibilidade inicial',
    ],
    verdict: 'Excelente kit para iniciar uma rotina de skincare profissional em casa.',
    rating: 4.6,
    reviewCount: 0,
    clickCount: 756,
    currentPrice: 79.90,
    originalPrice: 149.90,
    discount: 47,
    status: 'active',
    isFeatured: false,
    isTopRated: true,
    publishedAt: new Date('2024-02-10'),
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'prod-5',
    slug: 'mochila-antifurto-notebook',
    name: 'Mochila Antifurto para Notebook 15.6"',
    description: 'Mochila com design antifurto, bolso traseiro oculto e zíperes escondidos. Compartimento acolchoado para notebook até 15.6", porta USB externa para carregamento, tecido impermeável e alças ergonômicas. Ideal para trabalho e viagens.',
    shortDescription: 'Mochila impermeável antifurto com porta USB e compartimento notebook',
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80',
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&q=80',
    ],
    categoryId: 'cat-4',
    tags: ['mochila', 'notebook', 'antifurto', 'viagem'],
    pros: [
      'Design antifurto eficiente',
      'Impermeável',
      'Muito confortável',
      'Porta USB prática',
    ],
    cons: [
      'Capacidade limitada para viagens longas',
      'Cor escura única disponível',
    ],
    verdict: 'Perfeita para uso urbano diário. Segurança e praticidade em um só produto.',
    rating: 4.4,
    reviewCount: 0,
    clickCount: 543,
    currentPrice: 89.90,
    originalPrice: 159.90,
    discount: 44,
    status: 'active',
    isFeatured: true,
    isTopRated: false,
    publishedAt: new Date('2024-02-15'),
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'prod-6',
    slug: 'tenis-corrida-ultra-boost',
    name: 'Tênis de Corrida Ultra Boost Masculino',
    description: 'Tênis de corrida de alta performance com tecnologia de amortecimento Ultra Boost, solado Continental de borracha para máxima aderência, cabedal em malha respirável Primeknit e sistema de amarração adaptativo. Peso leve de apenas 310g.',
    shortDescription: 'Tênis running com amortecimento Ultra Boost e solado Continental',
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500&q=80',
    ],
    categoryId: 'cat-4',
    tags: ['tênis', 'corrida', 'esporte', 'boost'],
    pros: [
      'Amortecimento excepcional',
      'Muito leve e confortável',
      'Solado durável',
      'Design moderno',
    ],
    cons: [
      'Preço elevado',
      'Pode ser quente em dias muito quentes',
    ],
    verdict: 'Um dos melhores tênis de corrida do mercado. Vale o investimento para corredores sérios.',
    rating: 4.9,
    reviewCount: 0,
    clickCount: 1890,
    currentPrice: 199.90,
    originalPrice: 329.90,
    discount: 39,
    status: 'active',
    isFeatured: false,
    isTopRated: true,
    publishedAt: new Date('2024-01-25'),
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2026-02-12'),
  },
]

// ===========================================
// PRODUCT LINKS
// ===========================================

export const productLinks: ProductLink[] = [
  // Fone Bluetooth
  {
    id: 'link-1',
    productId: 'prod-1',
    storeId: 'store-1',
    url: 'https://amazon.com.br/dp/FONE123',
    shortCode: 'fone-amazon',
    price: 189.90,
    originalPrice: 349.90,
    discount: 46,
    currency: 'BRL',
    status: 'active',
    priority: 1,
    clickCount: 850,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'link-2',
    productId: 'prod-1',
    storeId: 'store-2',
    url: 'https://shopee.com.br/fone-premium',
    shortCode: 'fone-shopee',
    price: 199.90,
    originalPrice: 349.90,
    discount: 43,
    currency: 'BRL',
    status: 'active',
    priority: 2,
    clickCount: 400,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2026-02-01'),
  },
  // Smartwatch
  {
    id: 'link-3',
    productId: 'prod-2',
    storeId: 'store-3',
    url: 'https://mercadolivre.com.br/smartwatch',
    shortCode: 'watch-ml',
    price: 299.90,
    originalPrice: 499.90,
    discount: 40,
    currency: 'BRL',
    status: 'active',
    priority: 1,
    clickCount: 650,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'link-4',
    productId: 'prod-2',
    storeId: 'store-1',
    url: 'https://amazon.com.br/dp/WATCH456',
    shortCode: 'watch-amazon',
    price: 319.90,
    originalPrice: 499.90,
    discount: 36,
    currency: 'BRL',
    status: 'active',
    priority: 2,
    clickCount: 240,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2026-02-10'),
  },
  // Air Fryer
  {
    id: 'link-5',
    productId: 'prod-3',
    storeId: 'store-1',
    url: 'https://amazon.com.br/dp/AIRFRYER789',
    shortCode: 'airfryer-amazon',
    price: 249.90,
    originalPrice: 399.90,
    discount: 38,
    currency: 'BRL',
    status: 'active',
    priority: 1,
    clickCount: 1500,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'link-6',
    productId: 'prod-3',
    storeId: 'store-4',
    url: 'https://magazineluiza.com.br/airfryer',
    shortCode: 'airfryer-magalu',
    price: 269.90,
    originalPrice: 399.90,
    discount: 33,
    currency: 'BRL',
    status: 'active',
    priority: 2,
    clickCount: 600,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2026-02-15'),
  },
  // Kit Skincare
  {
    id: 'link-7',
    productId: 'prod-4',
    storeId: 'store-2',
    url: 'https://shopee.com.br/skincare-kit',
    shortCode: 'skincare-shopee',
    price: 79.90,
    originalPrice: 149.90,
    discount: 47,
    currency: 'BRL',
    status: 'active',
    priority: 1,
    clickCount: 500,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2026-02-01'),
  },
  // Mochila
  {
    id: 'link-8',
    productId: 'prod-5',
    storeId: 'store-1',
    url: 'https://amazon.com.br/dp/MOCHILA321',
    shortCode: 'mochila-amazon',
    price: 89.90,
    originalPrice: 159.90,
    discount: 44,
    currency: 'BRL',
    status: 'active',
    priority: 1,
    clickCount: 400,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'link-9',
    productId: 'prod-5',
    storeId: 'store-2',
    url: 'https://shopee.com.br/mochila-antifurto',
    shortCode: 'mochila-shopee',
    price: 94.90,
    originalPrice: 159.90,
    discount: 41,
    currency: 'BRL',
    status: 'active',
    priority: 2,
    clickCount: 143,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2026-02-01'),
  },
  // Tênis
  {
    id: 'link-10',
    productId: 'prod-6',
    storeId: 'store-3',
    url: 'https://mercadolivre.com.br/tenis-boost',
    shortCode: 'tenis-ml',
    price: 199.90,
    originalPrice: 329.90,
    discount: 39,
    currency: 'BRL',
    status: 'active',
    priority: 1,
    clickCount: 1200,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2026-02-12'),
  },
  {
    id: 'link-11',
    productId: 'prod-6',
    storeId: 'store-1',
    url: 'https://amazon.com.br/dp/TENIS654',
    shortCode: 'tenis-amazon',
    price: 219.90,
    originalPrice: 329.90,
    discount: 33,
    currency: 'BRL',
    status: 'active',
    priority: 2,
    clickCount: 690,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2026-02-12'),
  },
]

// ===========================================
// COUPONS
// ===========================================

export const coupons: Coupon[] = [
  {
    id: 'coupon-1',
    code: 'AMAZON10',
    storeId: 'store-1',
    title: '10% OFF em Eletrônicos',
    description: 'Desconto de 10% em produtos eletrônicos selecionados da Amazon',
    discountType: 'percentage',
    discountValue: 10,
    discountText: '10% OFF',
    minPurchase: 100,
    status: 'active',
    isVerified: true,
    isExclusive: false,
    usageCount: 1250,
    successRate: 92,
    expiresAt: new Date('2026-03-31'),
    lastVerifiedAt: new Date('2026-02-20'),
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2026-02-20'),
  },
  {
    id: 'coupon-2',
    code: 'FRETEGRATIS',
    storeId: 'store-2',
    title: 'Frete Grátis Shopee',
    description: 'Frete grátis para compras acima de R$ 50 na Shopee',
    discountType: 'freeShipping',
    discountText: 'Frete Grátis',
    minPurchase: 50,
    status: 'active',
    isVerified: true,
    isExclusive: true,
    usageCount: 3420,
    successRate: 88,
    expiresAt: new Date('2026-04-15'),
    lastVerifiedAt: new Date('2026-02-22'),
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2026-02-22'),
  },
  {
    id: 'coupon-3',
    code: 'ML50OFF',
    storeId: 'store-3',
    title: 'R$ 50 OFF Mercado Livre',
    description: 'R$ 50 de desconto em compras acima de R$ 200',
    discountType: 'fixed',
    discountValue: 50,
    discountText: 'R$ 50 OFF',
    minPurchase: 200,
    status: 'active',
    isVerified: true,
    isExclusive: false,
    usageCount: 890,
    successRate: 85,
    expiresAt: new Date('2026-03-15'),
    lastVerifiedAt: new Date('2026-02-18'),
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2026-02-18'),
  },
  {
    id: 'coupon-4',
    code: 'MAGALU15',
    storeId: 'store-4',
    title: '15% OFF Magazine Luiza',
    description: '15% de desconto em eletrodomésticos na Magazine Luiza',
    discountType: 'percentage',
    discountValue: 15,
    discountText: '15% OFF',
    maxDiscount: 200,
    status: 'active',
    isVerified: true,
    isExclusive: false,
    usageCount: 560,
    successRate: 90,
    expiresAt: new Date('2026-03-20'),
    lastVerifiedAt: new Date('2026-02-21'),
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2026-02-21'),
  },
  {
    id: 'coupon-5',
    code: 'PRIMEIRACOMPRA',
    storeId: 'store-2',
    title: 'R$ 20 OFF Primeira Compra',
    description: 'R$ 20 de desconto para novos usuários da Shopee',
    discountType: 'fixed',
    discountValue: 20,
    discountText: 'R$ 20 OFF',
    minPurchase: 30,
    status: 'active',
    isVerified: true,
    isExclusive: true,
    usageCount: 2100,
    successRate: 95,
    expiresAt: new Date('2026-06-30'),
    lastVerifiedAt: new Date('2026-02-23'),
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2026-02-23'),
  },
  {
    id: 'coupon-6',
    code: 'TECHWEEK',
    storeId: 'store-1',
    title: '20% OFF Tech Week',
    description: 'Semana Tech Amazon com 20% de desconto em gadgets',
    discountType: 'percentage',
    discountValue: 20,
    discountText: '20% OFF',
    categoryId: 'cat-1',
    status: 'active',
    isVerified: true,
    isExclusive: false,
    usageCount: 780,
    successRate: 87,
    expiresAt: new Date('2026-03-10'),
    lastVerifiedAt: new Date('2026-02-24'),
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2026-02-24'),
  },
]

// ===========================================
// REVIEWS
// ===========================================

export const reviews: Review[] = [
  {
    id: 'review-1',
    productId: 'prod-1',
    userId: 'user-1',
    authorName: 'Maria Silva',
    rating: 5,
    title: 'Melhor fone que já tive!',
    content: 'O cancelamento de ruído é incrível, uso no ônibus e não escuto nada. A bateria dura muito mesmo, carrego uma vez por semana. Super recomendo para quem trabalha em ambientes barulhentos.',
    pros: ['Cancelamento de ruído excelente', 'Bateria dura muito', 'Muito confortável'],
    cons: ['Estojo um pouco grande'],
    isVerified: true,
    purchaseSource: 'Amazon',
    helpfulCount: 42,
    notHelpfulCount: 2,
    status: 'approved',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-01'),
  },
  {
    id: 'review-2',
    productId: 'prod-1',
    userId: 'user-2',
    authorName: 'João Santos',
    rating: 4,
    title: 'Ótimo custo-benefício',
    content: 'Som muito bom pra faixa de preço. O único ponto negativo é que o estojo é meio grande, mas nada absurdo. Uso todo dia no trabalho e estou muito satisfeito.',
    pros: ['Som de qualidade', 'Preço justo', 'Bluetooth estável'],
    cons: ['Estojo grande', 'Poderia ter mais cores'],
    isVerified: true,
    purchaseSource: 'Shopee',
    helpfulCount: 28,
    notHelpfulCount: 1,
    status: 'approved',
    createdAt: new Date('2026-02-05'),
    updatedAt: new Date('2026-02-05'),
  },
  {
    id: 'review-3',
    productId: 'prod-1',
    userId: 'user-3',
    authorName: 'Ana Costa',
    rating: 5,
    title: 'Superou minhas expectativas',
    content: 'Comprei com receio por ser mais barato que outras marcas, mas a qualidade é surpreendente. Recomendo muito! Já indiquei para vários amigos.',
    isVerified: false,
    helpfulCount: 35,
    notHelpfulCount: 3,
    status: 'approved',
    createdAt: new Date('2026-02-10'),
    updatedAt: new Date('2026-02-10'),
  },
  {
    id: 'review-4',
    productId: 'prod-3',
    userId: 'user-4',
    authorName: 'Pedro Oliveira',
    rating: 5,
    title: 'Air fryer perfeita',
    content: 'Faz de tudo! Batata frita perfeita, frango crocante, até bolo dá pra fazer. Fácil de limpar também. Melhor compra que fiz nos últimos tempos.',
    pros: ['Versátil', 'Fácil de limpar', 'Comida crocante', 'Capacidade boa'],
    isVerified: true,
    purchaseSource: 'Amazon',
    helpfulCount: 56,
    notHelpfulCount: 0,
    status: 'approved',
    createdAt: new Date('2026-02-15'),
    updatedAt: new Date('2026-02-15'),
  },
  {
    id: 'review-5',
    productId: 'prod-2',
    userId: 'user-5',
    authorName: 'Carla Lima',
    rating: 4,
    title: 'Bom smartwatch para esportes',
    content: 'GPS funciona bem, monitora corrida direitinho. A tela é bonita e legível mesmo sob sol forte. Só falta NFC pra pagamento, mas no geral é excelente.',
    pros: ['GPS preciso', 'Tela bonita', 'Bateria boa'],
    cons: ['Sem NFC', 'App poderia melhorar'],
    isVerified: true,
    purchaseSource: 'Mercado Livre',
    helpfulCount: 19,
    notHelpfulCount: 1,
    status: 'approved',
    createdAt: new Date('2026-02-18'),
    updatedAt: new Date('2026-02-18'),
  },
]
