backend:
  name: github
  repo: sgcsequidaidecompras/sgcsequidaidecompras
  branch: main
  site_domain: sgcsequidaidecompras.vercel.app
  base_url: https://sgcsequidaidecompras.vercel.app
  auth_endpoint: api/auth

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "data"
    create: true
    extension: json
    slug: "{{id}}"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Nome", name: "nome", widget: "string" }
      - { label: "Descrição", name: "descricao", widget: "text" }
      - { label: "Imagem", name: "imagem", widget: "string" }
      - { label: "Preço", name: "preco", widget: "string" }
      - { label: "Avaliação", name: "avaliacao", widget: "number" }
      - { label: "Loja", name: "loja", widget: "string" }
      - { label: "Link", name: "linkAfiliado", widget: "string" }
